name: Run Test Suite

on:
  workflow_dispatch:
    inputs: 
      CONFIGURATION:
        description: 'Release configuration for the build'
        type: string
        default: Release
      DOTNET_VERSION:
        description: 'Dotnet SDK Version to use'
        type: string
        default: 8.0.x
      PROJECT_PATH:
        description: 'Directory for the test project'
        type: string
        default: "./test/Flattery.Tests/Flattery.Tests.csproj"
  workflow_call:
    inputs: 
      CONFIGURATION:
        description: 'Release configuration for the build'
        type: string
        required: true
        default: Release
      DOTNET_VERSION:
        description: 'Dotnet SDK Version to use'
        type: string
        required: true
        default: 8.0.x
      PROJECT_PATH:
        description: 'Directory for the test project'
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Using .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Run Test Suite
        run: dotnet test ${{ inputs.PROJECT_PATH }} --configuration ${{ inputs.CONFIGURATION }}
